export const COUNTRIES = [
  { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Germany' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'PL', label: 'Poland' },
  { value: 'RO', label: 'Romania' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'BE', label: 'Belgium' },
  { value: 'GR', label: 'Greece' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'SE', label: 'Sweden' },
  { value: 'PT', label: 'Portugal' },
  { value: 'HU', label: 'Hungary' },
  { value: 'AT', label: 'Austria' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'DK', label: 'Denmark' },
  { value: 'FI', label: 'Finland' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'IE', label: 'Ireland' },
  { value: 'HR', label: 'Croatia' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'LV', label: 'Latvia' },
  { value: 'EE', label: 'Estonia' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MT', label: 'Malta' }
];

export const GROUPS = [
  { value: 'EPP', label: 'European People\'s Party (EPP)', short_label: 'EPP' },
  { value: 'RENEW', label: 'Renew Europe (Renew)', short_label: 'Renew' },
  { value: 'SD', label: 'Progressive Alliance of Socialists and Democrats (S&D)', short_label: 'S&D' },
  { value: 'ECR', label: 'European Conservatives and Reformists (ECR)', short_label: 'ECR' },
  { value: 'NI', label: 'Non-attached Members (NI)', short_label: 'NI' },
  { value: 'ESN', label: 'Europe of Sovereign Nations (ESN)', short_label: 'ESN' },
  { value: 'GUE_NGL', label: 'The Left in the European Parliament (GUE/NGL)', short_label: 'GUE/NGL' },
  { value: 'GREEN_EFA', label: 'Greens/European Free Alliance (Greens/EFA)', short_label: 'Greens/EFA' },
  { value: 'PFE', label: 'Patriots for Europe (PFE)', short_label: 'PFE' },
  { value: 'ID', label: 'Identity and Democracy (ID)', short_label: 'ID' }
]; 